---
title: "People"
---
#### [Home](index.html) &emsp; [Research](research.html) &emsp; [Prejudice and Persuasion Processes Lab](ppplab.html) &emsp; [People](people.html)  &emsp; [CV](https://drive.google.com/file/d/1byZ4jXgb_iDk7IzKmI9vH05xxJi2jJIJ/view?usp=sharing)

##PI
###Koji Takahashi
Doctoral Candidate in Psychology </br>
NSF Graduate Research Fellow </br>
M.S. in Psychology, University of Michigan, 2018 </br>
B.A. in Psychology, University of California, Berkeley, 2014

##Current Research Assistants
###Danielle Buma
B.A. in Sociology and Art History </br>
University of California, Davis Class of 2015

##Former Research Assistants
###Angelle Antoun
B.S. in Biopsychology, Cognition, and Neuroscience </br>
University of Michigan Class of 2017

###Isis Burgdorf
University of Michigan Class of 2020

###Isabel Chaney
University of Michigan Class of 2022

###Bethany Haefner
B.A. in Psychology </br>
University of Michigan Class of 2017

###Andrea Janis
B.A. in Psychology </br>
University of Michigan Class of 2017

###Hannah Lahti
B.A. in Psychology </br>
University of Michigan Class of 2017

###Jordan Sachs

###Raivynn Smith
Program Specialist at University of Michigan </br>
B.A. in Psychology </br>
University of Michigan Class of 2017

###Lia Williams
B.A. in Psychology </br>
Kalamazoo College Class of 2018

###Evon Yao
University of Michigan Class of 2020

###Sethe Zachman
University of Michigan Class of 2019

##Collaborators
###Allison Earl
Assistant Professor of Psychology </br>
University of Michigan

###Denise Sekaquaptewa
Professor of Psychology </br>
University of Michigan

###[Hakeem J. Jefferson](https://hakeemjefferson.com/)
Assistant Professor of Political Science </br>
Stanford University

###[Nicholas M. Michalak](http://nickmichalak.com/index.html)
Doctoral Candidate in Psychology </br>
University of Michigan

###Peter Felsman
Doctoral Candidate in Psychology and Social Work </br>
University of Michigan
