---
title: "Prejudice and Persuasion Processes (PPP) Lab"
---
# [Home](index.html) &emsp; [Research](research.html) &emsp; [Prejudice and Persuasion Processes Lab](ppplab.html) &emsp; [People](people.html) 

##Lab Overview
The Prejudice and Persuasion Processes (PPP) Lab studies the role of stigma and prejudice in processes of attitude formation, expression, and change. The lab uses a variety of research methods to study these processes in the domains of health, education, and politics. This work is done in conjunction with the [Stereotyping and Prejudice Research Interest Group (SPRIG)](https://sites.google.com/a/umich.edu/denise-sekaquaptewa/home) run by Dr. Denise Sekaquaptewa and the [Health, Attitudes, and Influence Lab (HAILab)](http://hailab.psych.lsa.umich.edu/) run by Dr. Allison Earl. 

##For Research Assistants and Volunteers
Training and mentorship is an important goal of this lab. My role as PI for the PPP Lab is to train research assistants in experimental research methods and provide them with a quality educational experience. To this end, research assistants will have the opportunity to work on a variety of tasks at different stages of the research process. In the past, we have also conducted mini workshops or discussion sessions to build skills outside of our regular lab work. These typically depend on student interest, but topics have included data analysis, academic writing, literature reviews, and methodology reform. 
Anyone interested in becoming a research assistant can find more information in the [PPP Lab syllabus](link to come). 