---
title: "Research"
---

Research Statement

My research examines how stigma influences the way people actively shape their attitudes. I am primarily interested in understanding (a) how people gauge what others think about stigmatized groups and (b) the impact this has on how they attend to and process stigma-relevant persuasive messages (e.g. messages about information about discrimination, inequality, and diversity). This research aims to advance a theoretical understanding of the affective, attitudinal, and identity-based processes that collectively guide attitude formation, expression, and change. Drawing predominantly from social psychology, my work also integrates perspectives from sociology, political science, and communications to ground theories of basic psychological processes in broader social contexts. To this end, I use a variety of methods (lab experiments, surveys, field studies) to study these processes across social identities (gender, race, health status) and domains (education, politics, health). Ultimately, I apply this work to promote more hospitable and inclusive social environments in an increasingly contentious political climate. 

Primary Research Lines
I examine my primary research questions through in three distinct, but related research lines. 

I. Social and Institutional Influences on Receptivity to Gender Diversity Messages
This research tests features of the social environment and institutional practices that impact how receptive people are to gender diversity messages (e.g. Sekaquaptewa, Takahashi, Malley, & Herzog, under review). My focus is on both the types of social information that impacts message receptivity as well as the specific psychological processes that underlies these effects. For example, we are currently investigating antecedents and consequences of perceived trade-offs between gender diversity and institutional excellence. This research draws on insights from research on intergroup relations, attitudes, and interventions. 

II. Perceived Anti-White Bias and Attitudes about Racial Inequality
This research applies theories of message reception and processing (e.g. Takahashi & Earl, under review) to understand how perceptions of anti-White bias shapes how White people engage with information about racial inequality. I integrate perspectives from social psychology, sociology, and political science to develop and test a theoretical framework for the role of White identity, power, and racial/political attitudes in shaping message reception and processing among Whites.

III. Social Cues and Appraisals of Potential Bias
I also examine the types of social information people use to shape their appraisal of the ambiguously biased behavior of others. We examine the social cues people attend to or discount when they witness potential instances of bias. This work also examines how these appraisals shape people’s emotional reactions to bias, their sympathy for its targets, and their willingness to confront it. 
